networks:
  iskprinter:
    driver: bridge
services:
  database-populator:
    build:
      context: ./database-populator
    container_name: database-populator
    depends_on:
      - postgres
    environment:
      ISKPRINTER_POSTGRES_DATABASE_NAME: iskprinter
      ISKPRINTER_POSTGRES_HOSTNAME: iskprinter-postgres
      ISKPRINTER_POSTGRES_PASSWORD_PATH: /run/secrets/postgres-credentials/password
      ISKPRINTER_POSTGRES_USERNAME_PATH: /run/secrets/postgres-credentials/username
    networks:
      - iskprinter
    volumes:
      - ./secrets/postgres-credentials/database-populator/password:/run/secrets/postgres-credentials/password
      - ./secrets/postgres-credentials/database-populator/username:/run/secrets/postgres-credentials/username
  postgres:
    command:
      - /usr/bin/env
      - bash
      - -eu
      - -o
      - pipefail
      - -c
      - |
        # I'm not sure why this can't be placed beside "-eu" above.
        set -m

        # Start postgres with the default entrypoint and command.
        docker-entrypoint.sh postgres &

        # Confirm that the application database and the non-admin users exist.
        echo "Creating database and users..."
        /run/config-maps/create-databases-and-users.sh

        # Bring the postgres process back to the foreground.
        fg
    container_name: iskprinter-postgres
    entrypoint: []
    environment:
      ISKPRINTER_POSTGRES_DATABASE_ISKPRINTER_NAME: iskprinter
      ISKPRINTER_POSTGRES_DATABASE_SUPERSET_NAME: superset
      ISKPRINTER_POSTGRES_USER_DATABASE_POPULATOR_PASSWORD_PATH: /run/secrets/postgres-credentials/database-populator/password
      ISKPRINTER_POSTGRES_USER_DATABASE_POPULATOR_USERNAME_PATH: /run/secrets/postgres-credentials/database-populator/username
      ISKPRINTER_POSTGRES_USER_SUPERSET_PASSWORD_PATH: /run/secrets/postgres-credentials/superset/password
      ISKPRINTER_POSTGRES_USER_SUPERSET_USERNAME_PATH: /run/secrets/postgres-credentials/superset/username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-credentials/admin/password
      POSTGRES_USER_FILE: /run/secrets/postgres-credentials/admin/username
    healthcheck:
      test:
        - CMD
        - pg_isready
    hostname: iskprinter-postgres
    # Superset doesn't support Postgres 17 yet. Refer to https://superset.apache.org/docs/configuration/configuring-superset#setting-up-a-production-metadata-database.
    image: docker.io/library/postgres:16
    networks:
      - iskprinter
    volumes:
      - ./postgres/create-databases-and-users.sh:/run/config-maps/create-databases-and-users.sh
      - ./secrets/postgres-credentials/admin/password:/run/secrets/postgres-credentials/admin/password
      - ./secrets/postgres-credentials/admin/username:/run/secrets/postgres-credentials/admin/username
      - ./secrets/postgres-credentials/database-populator/password:/run/secrets/postgres-credentials/database-populator/password
      - ./secrets/postgres-credentials/database-populator/username:/run/secrets/postgres-credentials/database-populator/username
      - ./secrets/postgres-credentials/superset/password:/run/secrets/postgres-credentials/superset/password
      - ./secrets/postgres-credentials/superset/username:/run/secrets/postgres-credentials/superset/username
      - postgres:/var/lib/postgresql/data
  superset:
    build:
      context: ./superset
    container_name: iskprinter-superset
    depends_on:
      - postgres
    environment:
      ISKPRINTER_POSTGRES_DATABASE_NAME: superset
      ISKPRINTER_POSTGRES_HOSTNAME: iskprinter-postgres
      ISKPRINTER_POSTGRES_PASSWORD_PATH: /run/secrets/postgres-credentials/password
      ISKPRINTER_POSTGRES_USERNAME_PATH: /run/secrets/postgres-credentials/username
      ISKPRINTER_SUPERSET_ADMIN_PASSWORD_PATH: /run/secrets/superset-credentials/admin/password
      SUPERSET_SECRET_KEY_PATH: /run/secrets/superset-secret-key
    networks:
      - iskprinter
    ports:
      - "[::1]:8088:8088"
      - 127.0.0.1:8088:8088
    volumes:
      - ./secrets/postgres-credentials/superset/password:/run/secrets/postgres-credentials/password
      - ./secrets/postgres-credentials/superset/username:/run/secrets/postgres-credentials/username
      - ./secrets/superset-credentials/admin/password:/run/secrets/superset-credentials/admin/password
      - ./secrets/superset-secret-key:/run/secrets/superset-secret-key
volumes:
  postgres: {}
