apiVersion: v1
kind: Secret
metadata:
  name: database
  labels:
{{ include "iskprinter.labels" . | indent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.database.mongoInitdbRootUsername | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ required "Argument --set database.mongoInitdbRootPassword=<mongo-initdb-root-password> is required." .Values.database.mongoInitdbRootPassword | b64enc }}
