apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
{{ include "iskprinter.labels" . | indent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
      name: mongodb
  clusterIP: None
  selector:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: {{ .Release.Name }}
