apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  labels:
{{ include "iskprinter.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ required "Argument --set host=<host> is required." .Values.hostname }}
      http:
        paths:
          - path: {{ .Values.frontend.ingress.path }}
            backend:
              serviceName: frontend
              servicePort: {{ .Values.frontend.service.port }}
