apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
{{ include "iskprinter.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-client-credentials
                  key: id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-client-credentials
                  key: secret
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: url
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
