apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  labels:
{{ include "iskprinter.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ required "Argument --set host=<url> is required." $.Values.host | quote }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            backend:
              serviceName: api
              servicePort: {{ .Values.api.service.port }}
