apiVersion: v1
kind: Secret
metadata:
  name: api
  labels:
{{ include "iskprinter.labels" . | indent 4 }}
type: Opaque
data:
  CLIENT_ID: {{ required "Argument --set api.clientId=<client-id> is required." .Values.api.clientId | b64enc }}
  CLIENT_SECRET: {{ required "Argument --set api.clientSecret=<client-secret> is required." .Values.api.clientSecret | b64enc }}
