apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  labels:
{{ include "iskprinter.labels" . | indent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
