api:
  replicaCount: 2
  image:
    repository: docker.io/iskprinter/api
    tag: '937e3e9'
    pullPolicy: IfNotPresent # default
  ingress:
    path: /api
  service:
    name: api
    type: ClusterIP # default
    port: 3000
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

database:
  replicaCount: 1
  mongoInitdbRootUsername: root
  image:
    repository: mongo
    tag: 4.4.1-bionic
    pullPolicy: IfNotPresent # default
  service:
    name: database
    type: ClusterIP # default
    port: 27017
  volume:
    capacity: 8Gi
    mountPath: /data/db
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

frontend:
  replicaCount: 2
  image:
    repository: docker.io/iskprinter/frontend
    tag: '06a36d7'
    pullPolicy: IfNotPresent # default
  ingress:
    path: /
  service:
    name: frontend
    type: ClusterIP # default
    port: 80
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

weeklyDownload:
  image:
    repository: docker.io/iskprinter/weekly-download
    tag: '802ea6a'
    pullPolicy: IfNotPresent # default
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
